export const WHATEVER: string = "WHATEVER";

export const CHARACTER_ANIMATION_CHANGED = "CHARACTER_ANIMATION_CHANGED";
export const ACTIVE_NAV_ITEM_CHANGED = "ACTIVE_NAV_ITEM_CHANGED"; //this doesn't work well, causes conflicts between autoscrolling and normal scrolling/nav link hilighting
export const JUST_CLICKED_NAV_ITEM = "JUST_CLICKED_NAV_ITEM"; 
export const SWITCHED_AUTOSCROLL = "SWITCHED_AUTOSCROLL";

export const NAV_ITEM_HIGHLIGHTED = "NAV_ITEM_HIGHLIGHTED";
export const NAV_ITEM_SELECTED = "NAV_ITEM_SELECTED";

export const SCROLLED = "SCROLLED";
export const SCROLL_DIRECTION_CANGED = "SCROLL_DIRECTION_CANGED";

export const TOGGLED_THEME = "TOGGLED_THEME";

export const TOGGLED_SHOWCASE_MODAL = "TOGGLED_SHOWCASE_MODAL";
export const SELECTED_SHOWCASE_ITEM = "SELECTED_SHOWCASE_ITEM";