"use strict";
exports.__esModule = true;
exports.CLOSING_SHOWCASE_MODAL = exports.SELECTED_SHOWCASE_ITEM = exports.TOGGLED_SHOWCASE_MODAL = exports.TOGGLED_THEME = exports.SCROLL_DIRECTION_CANGED = exports.SCROLLED = exports.NAV_ITEM_SELECTED = exports.NAV_ITEM_HIGHLIGHTED = exports.SWITCHED_AUTOSCROLL = exports.JUST_CLICKED_NAV_ITEM = exports.ACTIVE_NAV_ITEM_CHANGED = exports.CHARACTER_ANIMATION_CHANGED = exports.WHATEVER = void 0;
exports.WHATEVER = "WHATEVER";
exports.CHARACTER_ANIMATION_CHANGED = "CHARACTER_ANIMATION_CHANGED";
exports.ACTIVE_NAV_ITEM_CHANGED = "ACTIVE_NAV_ITEM_CHANGED"; //this doesn't work well, causes conflicts between autoscrolling and normal scrolling/nav link hilighting
exports.JUST_CLICKED_NAV_ITEM = "JUST_CLICKED_NAV_ITEM";
exports.SWITCHED_AUTOSCROLL = "SWITCHED_AUTOSCROLL";
exports.NAV_ITEM_HIGHLIGHTED = "NAV_ITEM_HIGHLIGHTED";
exports.NAV_ITEM_SELECTED = "NAV_ITEM_SELECTED";
exports.SCROLLED = "SCROLLED";
exports.SCROLL_DIRECTION_CANGED = "SCROLL_DIRECTION_CANGED";
exports.TOGGLED_THEME = "TOGGLED_THEME";
exports.TOGGLED_SHOWCASE_MODAL = "TOGGLED_SHOWCASE_MODAL";
exports.SELECTED_SHOWCASE_ITEM = "SELECTED_SHOWCASE_ITEM";
exports.CLOSING_SHOWCASE_MODAL = "CLOSING_SHOWCASE_MODAL";
